#!/usr/bin/env php
<?php
include "src/Dates/BirthDays.php";

$birthDate = "1975-07-05";
$days = new \Smarttalker\Dates\BirthDays($birthDate);
$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays\n";
